### ISSUE TITLE
The filters don't seem to work anymore with Starling 1.6

### ISSUE THREAD

**Issue by ypmits** [devon-o/Starling-Filters#5]
Just wanted to let you know that the filters don't seem to work anymore in latest Starling 1.6. Just seems like a shame for everyone who wants to use them. :) Great work btw.

**Comment by devon-o** [comment]
Thank you for the heads up (and for the comments). Do you know which filters specifically? I'm using a few (Vignette, Ansel, Bleach, and a couple others) in a mobile app I'm working on using the latest version of Starling and they're working fine.

**Comment by ypmits** [comment]
Hi there,

I've used the VCRFilter before successfully (on an older version of Starling, I think it was 1.4), it doesn't seem to be working now anymore with the 1.6.

**Comment by devon-o** [comment]
Cool. I will check it out.

**Comment by bwatanabe** [comment]
Hello, I'm able to use Blur and Ansel, but it looks like Chromakey and Sine aren't working either. Really amazing filters, sad they broke with the latest version!

**Comment by devon-o** [comment]
It would seem there are 2 issues going on. For some reason any filters that sample textures using the 'wrap' or 'repeat' flag will only work in Context3DProfile.BASELINE_CONSTRAINED mode. Another problem is that a change to Starling has made it so that some filters are applied to the entire power of two texture rather than just the visual part. I'm not sure if the issues are due to Starling or Flash Player updates.

**Comment by devon-o** [comment]
Hi Alan,
I forgot to put this up on Github (need to do that), but the problem
seems to be RectangularTextures. Many of the filters require wrapping,
but wrapping is not  allowed on RectangularTextures. Since v1.6,
Starling has attempted to be 'nice' to devs by automatically creating
RectangularTextures for any texture that is not a power of two
dimension-wise. Two ways around that (without hacking the Starling
source): always use textures that have power-of-two widths and
heights, or, when creating your textures, always set mip mapping to
true (mip mapping isn't allowed for RectangularTextures either, so it
will force Starling to create non RT's).
Hope that made some sense and helps out.
Kind regards,-devon

----- Original Message -----
